# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrett', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singerID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('intro', models.TextField(max_length=500)),
                ('picture', models.ImageField(null=True, upload_to='garrett')),
            ],
        ),
    ]
