# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrett', '0002_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth',
            field=models.CharField(max_length=50),
        ),
    ]
