# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrett', '0003_auto_20170507_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songID', models.IntegerField()),
                ('songName', models.CharField(max_length=120)),
                ('singerID', models.CharField(max_length=10)),
                ('songURL', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
