# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garrett', '0004_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
