# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garrett', '0006_auto_20170520_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commentPost',
        ),
    ]
